# -- 코드를 입력하세요
# SELECT A.AUTHOR_ID, AUTHOR_NAME, CATEGORY
# # ,
# # AS TOTAL_SALES
# FROM AUTHOR A
# JOIN BOOK B ON A.AUTHOR_ID = B.AUTHOR_ID
# JOIN BOOK_SALES C ON C.BOOK_ID = B.BOOK_ID
# WHERE YEAR(SALES_DATE)=2022 and MONTH(SALES_DATE)=1 

# 저자 별, 카테고리 별 매출액
WITH PROFIT AS (
SELECT B.CATEGORY, B.AUTHOR_ID, A.BOOK_ID, SALES, PRICE, 
    SALES * PRICE AS revenue
    FROM BOOK_SALES A
    JOIN BOOK B ON A.BOOK_ID = B.BOOK_ID
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
)

SELECT A.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(revenue) AS TOTAL_SALES
FROM PROFIT A 
JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
GROUP BY AUTHOR_NAME, CATEGORY
ORDER BY 1 ASC, 3 DESC