-- 코드를 입력하세요
WITH T AS (
    SELECT WRITER_ID,
    COUNT(*) AS CNT
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
)

SELECT USER_ID, NICKNAME, 
    CONCAT(CITY,' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS "전체주소",
    CONCAT(SUBSTRING(TLNO, 1, 3), '-', 
           SUBSTRING(TLNO, 4, 4), '-', 
           SUBSTRING(TLNO, 8, 4)) AS "전화번호"
FROM USED_GOODS_USER A
JOIN T ON T.WRITER_ID = A.USER_ID
WHERE T.CNT >=3
ORDER BY USER_ID DESC