-- 코드를 입력하세요
-- 년 월 성별 별 상품 구해 회원 수 
-- 성별 - user_info 없으면 제외
-- 년 월 - SALES_DATE에서 ? 

SELECT YEAR, MONTH, GENDER, 
    COUNT(DISTINCT USER_ID) AS USERS
     
FROM 
(SELECT 
    YEAR(A.SALES_DATE) AS YEAR,
    MONTH(A.SALES_DATE) AS MONTH,
    GENDER, 
    A.USER_ID
FROM ONLINE_SALE A
JOIN USER_INFO B ON A.USER_ID = B.USER_ID
WHERE B.GENDER IS NOT NULL) T
GROUP BY YEAR, MONTH, GENDER
ORDER BY 1, 2, 3