-- APNT_NO	PT_NAME	PT_NO	MCDP_CD	DR_NAME	APNT_YMD
-- APPOINTMENT, PATIENT.  / DOCTOR / APPOINTMENT


-- 흉부(CS) 취소되지 않은 기록 - 환자 정보와 Join
SELECT APNT_NO, PT_NAME, A.PT_NO, A.MCDP_CD, C.DR_NAME, APNT_YMD
FROM APPOINTMENT A
JOIN PATIENT B ON A.PT_NO = B.PT_NO
JOIN DOCTOR C ON C.DR_ID = A.MDDR_ID
WHERE YEAR(APNT_YMD) = 2022 AND MONTH(APNT_YMD) = 4 AND DAY(APNT_YMD) = 13
AND APNT_CNCL_YN = 'N' AND A.MCDP_CD = 'CS'
ORDER BY APNT_YMD ASC