-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, TOT AS TOTAL_SALES
FROM 
(SELECT *, SUM(PRICE) AS TOT
FROM USED_GOODS_BOARD A
LEFT JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
WHERE A.STATUS = 'DONE'
GROUP BY A.WRITER_ID) C
WHERE TOT >=700000
ORDER BY 3 ASC